config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'pages#home'
  get '/pages/home'

  resources :hospitals

  resources :doctors do
    resources :schedules
  end

  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :schedule
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    belongs_to :hospital
    has_many :schedules

    validates :name, presence: true
    validates :hospital_id, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
    has_many :doctors

    validates :name, presence: true
    validates :address, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :doctor
    has_many :bookings

    validates :date_start, presence: true
    validates :date_end, presence: true
    validate :date_end_after_date_start

    private
    def date_end_after_date_start
        return if date_end.blank? || date_start.blank?

        if date_end < date_start
            errors.add(:date_end, "must be after the date_start")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # !!! (devise's email is conflicted with facebook's email)
  # def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.email = auth.info.email
  #     user.password = Devise.friendly_token[0,20]
  #     user.name = auth.info.name
  #   end
  # end

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    protected

    def after_sign_in_path_for(resource)
        hospitals_path
    end
  
    def after_sign_out_path_for(resource)
        request.referrer
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if booking_slot_is_full?
        format.html { redirect_to doctors_path, alert: 'Sorry, maximum booking slot is exceeded. Please try again later'}
      elsif invalid_booking_time?
        format.html { redirect_to doctors_path, alert: 'Sorry, maximum booking time is 30 minutes before the schedule. Please try again later'}
      elsif @booking.save
        format.html { redirect_to doctors_path, notice: 'Booking was successfully created.' }
      end
    end
  end

  private
    def booking_slot_is_full?
      Schedule.find(@booking.schedule_id).bookings.count >= 10
    end

    def invalid_booking_time?
      seconds_diff = (Schedule.find(@booking.schedule_id).date_start - DateTime.now).to_i.abs
      minutes = seconds_diff / 60
      minutes < 30
    end

    def booking_params
      params.require(:booking).permit(:schedule_id, :patient_name, :email, :phone, :birthdate, :payment_method, :notes)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
    @hospitals = Hospital.all
  end

  def create
    @doctor = Doctor.new(doctor_params)
    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctors_path, notice: 'Doctor was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :hospital_id)
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = Hospital.all
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new(hospital_params)
    respond_to do |format|
      if @hospital.save
        format.html { redirect_to hospitals_path, notice: 'Hospital was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def hospital_params
      params.require(:hospital).permit(:name, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :get_doctor
  before_action :set_schedule, only: [:show]

  # def index
  #   @schedules = @doctor.schedules
  # end

  def show
    @booking = @schedule.bookings.build
    @bookings = Booking.where(schedule_id: @schedule.id)
  end

  def new
    # @schedule = Schedule.new
    # @doctors = Doctor.all

    @schedule = @doctor.schedules.build
  end

  def create
    @schedule = @doctor.schedules.build(schedule_params)
        respond_to do |format|
         if @schedule.save
            format.html { redirect_to doctor_path(@doctor), notice: 'Schedule was successfully created.' }
         else
            format.html { render :new }
      end
    end



    # @schedule = Schedule.new(schedule_params)
    # respond_to do |format|
    #   if @schedule.save
    #     doctor = Doctor.find(@schedule.doctor_id)
    #     format.html { redirect_to doctor, notice: 'Schedule was successfully created.' }
    #   else
    #     format.html { render :new }
    #   end
    # end
  end

  private
    def set_schedule
      # @schedule = Schedule.find(params[:id])
      @schedule = @doctor.schedules.find(params[:id])
    end

    def get_doctor
      @doctor = Doctor.find(params[:doctor_id])
    end

    def schedule_params
      params.require(:schedule).permit(:doctor_id, :date_start, :date_end)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
    
    def failure
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= collection_select(:doctor, :hospital_id, @hospitals, :id, :name, {:prompt => false}) %> 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/index.html.erb
<h1>Doctor</h1>

<table class="table table-striped table-responsive-md btn-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hospital</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.hospital.name %></td>
        <td><%= link_to "Show Schedules", doctor %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'New Doctor', new_doctor_path %>
</p>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<p>
  <%= link_to 'Back', doctors_path %>
</p>

app/views/doctors/show.html.erb
<h1>Doctor's Schedules</h1>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @doctor.hospital.name %>
</p>

<table class="table table-striped table-responsive-md btn-table">
  <thead>
    <tr>
      <th>Schedule ID</th>
      <th>Start</th>
      <th>End</th>
    </tr>
  </thead>
  <tbody>
    <% @doctor.schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.date_start %></td>
        <td><%= schedule.date_end %></td>
        <td><%= link_to "Booking", doctor_schedule_path(@doctor, schedule.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'New Schedule', new_doctor_schedule_path(@doctor) %>
</p>

<p>
  <%= link_to 'Back', doctors_path %>
</p>

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/index.html.erb
<h1>Hospital</h1>

<table class="table table-striped table-responsive-md btn-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'New Hospital', new_hospital_path %>
</p>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SehatQ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="/">SehatQ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/hospitals">Hospital</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/doctors">Doctor</a>
            </li>
          </ul>

          <p class="navbar-text float-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>

        </div>
      </div>
    </nav>

    <div class="container">

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

      <%= yield %>
    </div>

    <footer>
      <div class="container">
        SehatQ <%= Time.now.year %>
      </div>
    </footer>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>  
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <%= current_user.inspect %>
<% end %>

<% unless current_user %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<% else %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>

app/views/schedules/_booking.html.erb
<%= form_with(model: booking, local: true) do |form| %>
    <% if booking.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
 
       <ul>
      <% booking.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
    <% end %>

  <%= form.hidden_field :schedule_id, :value => booking.schedule.id %>

   <div class="field">
    <%= form.label :patient_name %>
    <%= form.text_field :patient_name %>
   </div>

   <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
   </div>

   <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
   </div>

   <div class="field">
    <%= form.label :birthdate %>
    <%= form.text_field :birthdate %>
   </div>
   
   <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method %>
   </div>

   <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
   </div>

   <div class="actions">
     <%= form.submit %>
   </div>
<% end %>

app/views/schedules/_form.html.erb
<%= form_with(model: [@doctor, schedule], local: true) do |form| %>
  <% if schedule.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>
 
       <ul>
      <% schedule.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>
 
   <div class="field">
    <%= form.label :doctor_id %>
    <%= form.text_field :doctor_id %>
   </div>
 
   <div class="field">
    <%= form.label :date_start %>
    <%= form.text_field :date_start %>
   </div>
 
   <div class="field">
    <%= form.label :date_end %>
    <%= form.text_field :date_end %>
   </div>
 
   <div class="actions">
     <%= form.submit %>
   </div>
 <% end %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

app/views/schedules/show.html.erb
<h1>Doctor Booking</h1>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @doctor.hospital.name %>
</p>

<table class="table table-striped table-responsive-md btn-table">
  <thead>
    <tr>
      <th>Schedule ID</th>
      <th>Start</th>
      <th>End</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @schedule.id %></td>
        <td><%= @schedule.date_start %></td>
        <td><%= @schedule.date_end %></td>
      </tr>
  </tbody>
</table>

<h3>Booking List</h3>
<table class="table table-striped table-responsive-md btn-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Booked at</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.patient_name %></td>
        <td><%= booking.email %></td>
        <td><%= booking.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Booking Form</h3>
<%= render 'booking', booking: @booking %>